# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ZIUPURWZhjJUe-OCMJ-y-Hd8ewnBp0k
"""

import pandas as pd
import numpy as np

hepatitis_data = pd.read_csv('https://raw.githubusercontent.com/datasets/hepatitis/master/data/hepatitis.csv')
hepatitis_data

# Identify numeric columns
numeric_columns = hepatitis_data.select_dtypes(include=['number']).columns

# Display missing values count before replacement
print("Missing Values Before Replacement:")
print(hepatitis_data[numeric_columns].isnull().sum())

# Replace missing values in numeric columns with their mean
hepatitis_data[numeric_columns] = hepatitis_data[numeric_columns].apply(lambda col: col.fillna(col.mean()))

# Display missing values count after replacement
print("\nMissing Values After Replacement:")
print(hepatitis_data[numeric_columns].isnull().sum())

hepatitis_data